Repository BiagioFesta/wtransport, pull requests merged in 2023-10, with the labels that each got.

#79 clippy: Fix filter_map_bool_then warning.
  wtransport-proto/src/ids.rs
Labels: enhancement

#80 config: allow passing custom tls configuration
  wtransport/src/config.rs
  wtransport/src/tls.rs
Labels: documentation, enhancement

#82 tls: make load Certificate async with tokio fs
  wtransport/Cargo.toml
  wtransport/examples/server.rs
  wtransport/src/config.rs
  wtransport/src/endpoint.rs
  wtransport/src/lib.rs
  wtransport/src/tls.rs
Labels: enhancement

#83 proto: API use Result<Option> instead of Option<Result>
  wtransport-proto/src/frame.rs
  wtransport-proto/src/stream.rs
  wtransport-proto/src/stream_header.rs
Labels: enhancement

#84 endpoint: local_addr method
  wtransport/src/endpoint.rs
Labels: enhancement, feature
